SELECT NOME_FORNECEDOR, PRECO FROM FORNECEDOR FDR
INNER JOIN FORNECIMENTO FNTO ON FNTO.CODIGO_FORNECEDOR = FDR.CODIGO_FORNECEDOR
INNER JOIN CARRO CAR ON FNTO.CODIGO_CARRO = CAR.CODIGO_CARRO
INNER JOIN PEÇA PEC ON FNTO.CODIGO_PECA = PEC.CODIGO_PEÇA
WHERE FDR.CIDADE = 'VITORIA' AND PEC.CODIGO_PEÇA = 'MOTOR'
AND CAR.CODIGO_CARRO = 'KOMBI';